<h1 align = "center"> Analysis of School Shootings in America

<img src='http://1.bp.blogspot.com/-dCWwvElzjqA/UgOnLNDBgYI/AAAAAAAAApY/WvZv586ju-M/s640/Dont+Shoot.jpg'>

In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [110]:
import plotly
from plotly.offline import init_notebook_mode, iplot
init_notebook_mode(connected=True)
import re

In [3]:
data= pd.read_csv('gun-violence-data_01-2013_03-2018.csv')
data.head()

,incident_id,date,state,city_or_county,address,n_killed,n_injured,incident_url,source_url,incident_url_fields_missing,...,participant_age,participant_age_group,participant_gender,participant_name,participant_relationship,participant_status,participant_type,sources,state_house_district,state_senate_district
0,461105,2013-01-01,Pennsylvania,Mckeesport,1506 Versailles Avenue and Coursin Street,0,4,http://www.gunviolencearchive.org/incident/461105,http://www.post-gazette.com/local/south/2013/0...,False,...,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||3::Male||4::Female,0::Julian Sims,NaN,0::Arrested||1::Injured||2::Injured||3::Injure...,0::Victim||1::Victim||2::Victim||3::Victim||4:...,http://pittsburgh.cbslocal.com/2013/01/01/4-pe...,NaN,NaN
1,460726,2013-01-01,California,Hawthorne,13500 block of Cerise Avenue,1,3,http://www.gunviolencearchive.org/incident/460726,http://www.dailybulletin.com/article/zz/201301...,False,...,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male,0::Bernard Gillis,NaN,0::Killed||1::Injured||2::Injured||3::Injured,0::Victim||1::Victim||2::Victim||3::Victim||4:...,http://losangeles.cbslocal.com/2013/01/01/man-...,62.0,35.0
2,478855,2013-01-01,Ohio,Lorain,1776 East 28th Street,1,3,http://www.gunviolencearchive.org/incident/478855,http://chronicle.northcoastnow.com/2013/02/14/...,False,...,0::25||1::31||2::33||3::34||4::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||2::Male||3::Male||4::Male,0::Damien Bell||1::Desmen Noble||2::Herman Sea...,NaN,"0::Injured, Unharmed, Arrested||1::Unharmed, A...",0::Subject-Suspect||1::Subject-Suspect||2::Vic...,http://www.morningjournal.com/general-news/201...,56.0,13.0
3,478925,2013-01-05,Colorado,Aurora,16000 block of East Ithaca Place,4,0,http://www.gunviolencearchive.org/incident/478925,http://www.dailydemocrat.com/20130106/aurora-s...,False,...,0::29||1::33||2::56||3::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Female||1::Male||2::Male||3::Male,0::Stacie Philbrook||1::Christopher Ratliffe||...,NaN,0::Killed||1::Killed||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,http://denver.cbslocal.com/2013/01/06/officer-...,40.0,28.0
4,478959,2013-01-07,North Carolina,Greensboro,307 Mourning Dove Terrace,2,2,http://www.gunviolencearchive.org/incident/478959,http://www.journalnow.com/news/local/article_d...,False,...,0::18||1::46||2::14||3::47,0::Adult 18+||1::Adult 18+||2::Teen 12-17||3::...,0::Female||1::Male||2::Male||3::Female,0::Danielle Imani Jameison||1::Maurice Eugene ...,3::Family,0::Injured||1::Injured||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,http://myfox8.com/2013/01/08/update-mother-sho...,62.0,27.0

### Data is given for 51 states

In [13]:
states = list(data['state'].unique())
len(states)

51

In [14]:
killed=[]
injured=[]
for i in states:
    s = data[(data['state']== i)]
    k = sum(s['n_killed'])
    killed.append(k)
    i = sum(s['n_injured'])
    injured.append(i)

### Killed vs injured

In [15]:
import plotly.plotly as py
import plotly.graph_objs as go

trace1 = go.Bar(
            x=states,
            y=killed,
            name = 'Killed'
    )
trace2 = go.Bar(
            x=states,
            y=injured,
            name = 'Injured'
    )

data = [trace1, trace2]
layout = go.Layout(
    barmode='group'
)

fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='grouped-bar')

### California has more number of deaths related to school shootings whereas Illinois has more injuries

In [52]:
#TOTAL CASUALITIES IS NUMBER OF DEATHS + NUMBER OF INJURIES
total =[x + y for x, y in zip(killed, injured)]

In [148]:
data = [go.Bar(x=states,y=total)]
py.iplot(data, title = 'Top States with highest number of Gun Violence',filename='basic-bar')

   <h2 align = "center">       The state of Illinois has suffered the most from the school shootings

<img src ='https://i2.cdn.turner.com/money/dam/assets/160203113813-welcome-to-illinois-sign-780x439.jpg'>

In [66]:
data= pd.read_csv('gun-violence-data_01-2013_03-2018.csv')

In [97]:
i = data.loc[data['state'] == 'Illinois',:]
city = list(i['city_or_county'].unique())

### Let us analyze the state of illinois(Land of Lincoln) by looking at its cities and counties

In [99]:
illinois_killed = {}
illinois_injured = {}
killed=[]
injured=[]
for j in city:
    s = i[(i['city_or_county']== j)]
    k = sum(s['n_killed'])
    illinois_killed[j] = k
    kk = sum(s['n_injured'])
    illinois_injured[j] = kk

### Remove the cities or counties with less than 10 deaths

In [111]:
illinois_killed.values()
i_k = {x:y for x,y in illinois_killed.items() if y>10}

In [128]:
data = [go.Bar(x=list(i_k.keys()),
            y=list(i_k.values()) ,
            marker=dict(color='#cc33ff'))]

py.iplot(data, filename='jupyter-basic_bar')

### Chicago is the most dangerous city for school going children in the USA

In [20]:
data= pd.read_csv('gun-violence-data_01-2013_03-2018.csv')

### When considering all cities

In [21]:
city = data['city_or_county'].value_counts()
city = city[:25]

In [27]:
d = [go.Bar(x=list(city.index),y=list(city.values),marker=dict(color='#ffff4d'))]
py.iplot(d,filename='babar')

### The school shootings in chicago seems to be very much higher than all other cities in the United States

<img src='http://s14544.pcdn.co/wp-content/uploads/2017/01/Chicago-Crime-1-660x496.jpg'>

### Lets analyze the guns used in these shootings

In [100]:
guns = data['gun_type']
guns = guns.dropna()
guns = [x for x in guns if x != '0::Unknown' and x!='0:Unknown']

In [156]:
allguns=[]
for i in guns:
    result = re.sub("\d+::", "", i)
    result = re.sub("\d+:", "", result)
    result = result.split("|")
    for j in result:
        allguns.append(j)

In [161]:
allguns = [x for x in allguns if x != 'Unknown']
allguns = [x for x in allguns if x]

In [168]:
from collections import Counter
allguns = Counter(allguns)
labels, values = zip(*allguns.items())

### Guns used in the shootings

In [171]:
d = [go.Bar(x=list(labels),y=list(values),marker=dict(color='#ff0055'))]
py.iplot(d,filename='babar')

### Handguns are the most used guns followed by 9mm and rifles

In [254]:
data= pd.read_csv('gun-violence-data_01-2013_03-2018.csv')
data.head()

,incident_id,date,state,city_or_county,address,n_killed,n_injured,incident_url,source_url,incident_url_fields_missing,...,participant_age,participant_age_group,participant_gender,participant_name,participant_relationship,participant_status,participant_type,sources,state_house_district,state_senate_district
0,461105,2013-01-01,Pennsylvania,Mckeesport,1506 Versailles Avenue and Coursin Street,0,4,http://www.gunviolencearchive.org/incident/461105,http://www.post-gazette.com/local/south/2013/0...,False,...,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||3::Male||4::Female,0::Julian Sims,NaN,0::Arrested||1::Injured||2::Injured||3::Injure...,0::Victim||1::Victim||2::Victim||3::Victim||4:...,http://pittsburgh.cbslocal.com/2013/01/01/4-pe...,NaN,NaN
1,460726,2013-01-01,California,Hawthorne,13500 block of Cerise Avenue,1,3,http://www.gunviolencearchive.org/incident/460726,http://www.dailybulletin.com/article/zz/201301...,False,...,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male,0::Bernard Gillis,NaN,0::Killed||1::Injured||2::Injured||3::Injured,0::Victim||1::Victim||2::Victim||3::Victim||4:...,http://losangeles.cbslocal.com/2013/01/01/man-...,62.0,35.0
2,478855,2013-01-01,Ohio,Lorain,1776 East 28th Street,1,3,http://www.gunviolencearchive.org/incident/478855,http://chronicle.northcoastnow.com/2013/02/14/...,False,...,0::25||1::31||2::33||3::34||4::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||2::Male||3::Male||4::Male,0::Damien Bell||1::Desmen Noble||2::Herman Sea...,NaN,"0::Injured, Unharmed, Arrested||1::Unharmed, A...",0::Subject-Suspect||1::Subject-Suspect||2::Vic...,http://www.morningjournal.com/general-news/201...,56.0,13.0
3,478925,2013-01-05,Colorado,Aurora,16000 block of East Ithaca Place,4,0,http://www.gunviolencearchive.org/incident/478925,http://www.dailydemocrat.com/20130106/aurora-s...,False,...,0::29||1::33||2::56||3::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Female||1::Male||2::Male||3::Male,0::Stacie Philbrook||1::Christopher Ratliffe||...,NaN,0::Killed||1::Killed||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,http://denver.cbslocal.com/2013/01/06/officer-...,40.0,28.0
4,478959,2013-01-07,North Carolina,Greensboro,307 Mourning Dove Terrace,2,2,http://www.gunviolencearchive.org/incident/478959,http://www.journalnow.com/news/local/article_d...,False,...,0::18||1::46||2::14||3::47,0::Adult 18+||1::Adult 18+||2::Teen 12-17||3::...,0::Female||1::Male||2::Male||3::Female,0::Danielle Imani Jameison||1::Maurice Eugene ...,3::Family,0::Injured||1::Injured||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,http://myfox8.com/2013/01/08/update-mother-sho...,62.0,27.0

In [255]:
d = data.groupby('date').sum()

In [259]:
d

,incident_id,n_killed,n_injured,incident_url_fields_missing,congressional_district,latitude,longitude,n_guns_involved,state_house_district,state_senate_district
date,,,,,,,,,,
2013-01-01,1400686,2,10,False,66.0,115.7012,-280.3266,2.0,118.0,48.0
2013-01-05,478925,4,0,False,6.0,39.6518,-104.8020,NaN,40.0,28.0
2013-01-07,957907,6,2,False,7.0,72.3545,-175.9337,2.0,134.0,38.0
2013-01-19,479363,5,0,False,1.0,34.9791,-106.7160,2.0,10.0,14.0
2013-01-21,958763,0,9,False,11.0,67.9091,-211.8016,NaN,104.0,12.0
2013-01-23,983825,2,9,False,10.0,74.3120,-161.9109,1.0,28.0,54.0
2013-01-25,479413,1,3,False,1.0,38.7067,-90.2494,1.0,76.0,4.0
2013-01-26,1438575,3,11,False,12.0,108.7046,-252.3186,2.0,129.0,31.0
2013-02-02,479573,0,5,False,9.0,35.0803,-89.8871,1.0,84.0,33.0
2013-02-03,479580,1,3,False,3.0,39.1236,-121.5830,1.0,3.0,4.0
2013-02-07,479592,0,4,False,2.0,41.7592,-87.5628,NaN,25.0,13.0
2013-02-09,479603,0,4,False,2.0,29.9563,-90.0676,1.0,93.0,4.0
2013-02-11,960638,4,6,False,6.0,77.8479,-197.7779,1.0,16.0,6.0
2013-02-12,480344,4,1,False,4.0,40.6008,-111.9030,NaN,44.0,8.0
2013-02-19,480358,4,3,False,46.0,33.8031,-117.9430,1.0,72.0,34.0
2013-02-21,480383,1,3,False,1.0,36.1722,-95.8778,NaN,77.0,34.0
2013-02-22,480401,0,4,False,3.0,42.9371,-85.6853,NaN,76.0,29.0
2013-02-23,480407,0,4,False,25.0,34.6666,-118.1310,NaN,36.0,21.0
2013-02-24,480443,0,8,False,2.0,32.8260,-83.6704,NaN,142.0,26.0
2013-03-02,481186,1,3,False,4.0,32.4420,-93.7726,NaN,3.0,39.0
2013-03-03,962406,2,6,False,13.0,74.5768,-167.6994,1.0,267.0,43.0
2013-03-04,481213,1,3,False,16.0,37.0857,-120.8280,1.0,21.0,12.0
2013-03-05,481220,1,3,False,7.0,39.7927,-86.0328,NaN,100.0,28.0
2013-03-07,481229,2,2,False,2.0,32.2649,-90.2141,1.0,71.0,29.0
2013-03-10,481237,0,5,False,5.0,38.9550,-94.5211,1.0,27.0,9.0
2013-03-11,482771,0,13,False,1.0,38.9062,-77.0099,4.0,NaN,NaN
2013-03-13,965657,8,4,False,71.0,76.2608,-192.3148,1.0,177.0,87.0
2013-03-14,482838,0,4,False,10.0,37.6260,-121.0110,NaN,21.0,12.0
2013-03-16,482926,0,7,False,9.0,38.2436,-121.3120,NaN,9.0,5.0
2013-03-17,965876,2,8,False,29.0,64.6499,-201.9497,NaN,94.0,30.0
...,...,...,...,...,...,...,...,...,...,...
2018-03-02,149795214,41,50,False,908.0,4422.0995,-10815.0381,164.0,6347.0,1952.0
2018-03-03,131839736,29,64,False,1081.0,3945.8937,-9574.5692,136.0,6377.0,2313.0
2018-03-04,166904994,32,67,False,958.0,4434.1182,-10617.4207,185.0,5847.0,1922.0
2018-03-05,203223090,51,61,False,1396.0,6312.9284,-14945.2022,234.0,8980.0,3093.0
2018-03-06,154384106,29,65,False,841.0,4530.4911,-10675.7052,165.0,6434.0,2136.0
2018-03-07,160950904,34,58,False,1059.0,4575.0617,-11428.4895,214.0,7394.0,2407.0
2018-03-08,143951152,24,61,False,806.0,3834.2557,-9443.5770,200.0,5636.0,1956.0
2018-03-09,146209983,37,65,False,919.0,3902.6304,-9277.3855,211.0,5359.0,1992.0
2018-03-10,167622267,43,66,False,848.0,4517.4788,-10618.0295,170.0,6386.0,2020.0
2018-03-11,154906054,36,73,False,868.0,4021.9073,-9563.8457,161.0,6151.0,1845.0
2018-03-12,187107512,46,79,False,1201.0,5068.4758,-12584.5602,258.0,6959.0,2497.0
2018-03-13,156171589,21,65,False,726.0,4158.1986,-9923.2290,252.0,5978.0,1913.0
2018-03-14,192687533,52,55,False,1070.0,5029.3742,-12009.7018,235.0,7962.0,2252.0
2018-03-15,176768797,25,72,False,989.0,4620.3961,-10904.4541,202.0,6853.0,2217.0
2018-03-16,134005575,30,52,False,674.0,3376.7112,-8132.8187,174.0,5154.0,1765.0
2018-03-17,190938483,36,104,False,967.0,5241.4629,-12592.3510,188.0,8023.0,2408.0
2018-03-18,212481572,40,98,False,1231.0,5515.0282,-13249.4858,205.0,6250.0,2282.0
2018-03-19,165414010,31,61,False,1006.0,4513.4681,-10699.3564,204.0,6589.0,2446.0
2018-03-20,161233224,36,64,False,881.0,4247.7884,-9632.9213,164.0,6378.0,2105.0
2018-03-21,162383316,38,70,False,887.0,4046.8494,-9618.1920,202.0,5919.0,1892.0
2018-03-22,181922082,29,69,False,1017.0,4249.6185,-10382.2647,194.0,6060.0,2164.0
2018-03-23,136797995,31,51,False,794.0,3285.3119,-8042.1595,155.0,5635.0,1628.0
2018-03-24,199398073,49,95,False,918.0,4742.8281,-10991.7767,216.0,5556.0,1674.0
2018-03-25,185462369,48,80,False,708.0,4326.7518,-9859.4229,203.0,5506.0,1890.0
2018-03-26,158582163,30,81,False,1026.0,4159.5230,-10162.0249,184.0,5792.0,2208.0
2018-03-27,145762685,18,57,False,742.0,3537.6161,-8538.5613,158.0,4307.0,1733.0
2018-03-28,189053638,42,69,False,930.0,4618.5833,-11195.5822,201.0,7399.0,2178.0
2018-03-29,141620184,33,69,False,850.0,3535.0982,-8388.4050,172.0,6646.0,1891.0
2018-03-30,123332723,41,49,False,711.0,3168.2250,-7636.9381,138.0,5137.0,1660.0
2018-03-31,142863067,53,75,False,811.0,3128.3383,-7590.0247,138.0,4957.0,1669.0

In [262]:
data = [go.Scatter(
          x=d.index,
          y=d['n_killed'])]

py.iplot(data)


killings = go.Scatter(
                x=d.index,
                y=d['n_killed'],
                name = "Killed",
                line = dict(color = '#17BECF'),
                opacity = 0.8)

injured = go.Scatter(
                x=d.index,
                y=d['n_injured'],
                name = "injured",
                line = dict(color = '#7F7F7F'),
                opacity = 0.8)

data = [killings,injured]

layout = dict(
    title = "Number of casualities with respect to time",
)

fig = dict(data=data, layout=layout)
py.iplot(fig, filename = "Manually Set Range")

## Sudden spike in the number of school shootings from the year 2013-2014

<img src='https://ichef.bbci.co.uk/news/660/cpsprodpb/2AFC/production/_100140011_hi045042704.jpg'>

### Researchers point out that owning a gun is an attribute of school shootings, but cannot be considered a cause in and of itself. Teens, of course, cannot legally purchase guns, but they can steal them from parents, buy them on the blackmarket, or obtain them through gang affiliations.



### While gun control advocates argue tougher legislation would reduce gun violence, others believe that stricter gun laws would not prevent criminals from getting their hands on weapons, whether guns or homemade explosives. Some mental health experts even argue that the push for greater legislation overshadows the much deeper and more complex mental health issues driving gun violence in schools.

<h1 align = "center"> THANK YOU